Debian package post-install-config.template - Support python3-six in Sid.
Newer Debian releases do not have python-six, but the Python 3 version
of that: python3-six, which caused a post install error creating Sid based
images when python-six could not be found.

As the post-install-config.sh script that is genereated from the
post-install-config.template can be running on Debian releases as far
back as 8 Jessie, it has to be aware of this.

So the solution is to try and install classic Python packages, and
if that fails, fail silently and try for the newer Python 3 versions
to provide the expected level of functionality.

Signed-off-by: Alex Doyle <adoyle@nvidia.com>

diff --git a/templates/debian-package/post-install-config.sh.template b/templates/debian-package/post-install-config.sh.template
--- a/templates/debian-package/post-install-config.sh.template
+++ b/templates/debian-package/post-install-config.sh.template
@@ -30,24 +30,31 @@ ulimit -n 10000
 apt-get update
 
 #
-# if python can't be installed, try python3
-# Success will vary by distribution...
+# As Python availability varies by release, try to install
+# classic Python and python-six to support older releases.
+# Print a success message if that worked and bury the error
+# message if it failed so the user isn't alarmed by the
+# retry for python3 and python3-six packages.
 #
-
+PYTHON_SIX_PACKAGE="python-six"
 DEBIAN_FRONTEND=noninteractive \
                apt-get install \
                --assume-yes \
                --no-install-recommends \
-               python 2>/dev/null
-if [ $? != 0 ];then
+               python > /dev/null 2>&1
+if [ $? = 0 ];then
+    echo "Installed classic Python package."
+else
     DEBIAN_FRONTEND=noninteractive \
                    apt-get install \
                    --assume-yes \
                    --no-install-recommends \
                    python3
+    # Newer Python = newer python six
+    PYTHON_SIX_PACKAGE="python3-six"
 fi
 # Packages for kernel build, but not essential for Debian packaging
-KERNEL_BUILD_PACKAGES=" build-essential python-six rsync gcc bc bison cpio flex kmod quilt u-boot-tools "
+KERNEL_BUILD_PACKAGES=" build-essential rsync gcc bc bison cpio flex kmod quilt u-boot-tools $PYTHON_SIX_PACKAGE "
 
 # Lintian checks code for errors or questionable implementations
 # in Debian packaging. Adds about 12MB to the container size
