due - Be very explicit about local sourcing
If DUE is not run from it's system installed location,
AND ./libdue is local, then source that libdue, and print
a notice that it is being used.

This fixes a bug in the previous logic where supplying an absolute
path to a local copy of due would pull in libdue from the directory
it was being invoked from.

This will still provide the ability to use a locally checked out
copy of DUE, rather than the one installed on the system, and it will
be very clear about which files are being used.

Signed-off-by: Alex Doyle <adoyle@nvidia.com>

diff --git a/due b/due
--- a/due
+++ b/due
@@ -9,16 +9,26 @@
 # If a piped operation fails, die on the first error.
 set -o pipefail
 
+INSTALLED_DUE_PATH="/usr/bin/due"
 INSTALLED_DUE_DIR="/usr/share/due"
 LIBRARY_FILE="/usr/lib/libdue"
-if [  -e ./libdue ];then
-    # Use local copy if it exists. We are running from a source
-    # checkout and probably want the current file, rather than
-    # the installed one
-    TOP_LEVEL_DIR=$(pwd)
-    LIBRARY_FILE="${TOP_LEVEL_DIR}/libdue"
-fi
 
+
+if [ "$0" != "$INSTALLED_DUE_PATH" ];then
+    if [  -e ./libdue ] && [ -e ./due ];then
+        # If both files are in the same directory,
+        # it is probably running from a source checkout
+        # should use the library from the corrent
+        # directory, rather than the installed one.
+        TOP_LEVEL_DIR=$(pwd)
+        LIBRARY_FILE="${TOP_LEVEL_DIR}/libdue"
+        # Let the user know they're using the local copy.
+        echo "Sourcing DUE files from [ $TOP_LEVEL_DIR ]"
+    else
+        echo "Cannot run $0. Missing files. Exiting."
+        exit 1
+    fi
+fi
 if [ ! -e "$LIBRARY_FILE"  ];then
     echo "ERROR! Failed to find [ $LIBRARY_FILE ]. Exiting."
     exit 1
