Image import - use 'load' with 'save' to import working images.
From the documentation, an image exported with 'save', which
preserves all filesystem layers, which is the safest course
of action for someone using a wrapper like DUE, should be
imported using 'load' which accounts for all that.

'export' and 'import' are separate commands which should not
be mixed and matched with 'save' and 'load'

Testing:
--------
 ./due --create --from debian:10 --description "Debian 10 example" \
  --name example-debian-10 --prompt Ex --tag example-debian-10 --use-template example
 ./due --run  <choose example>
 In a separate window
 due --manage --export-container extets
   <saves container as due-extest.tar>
 ./due -m --import-image  due-extest.tar
 ./due --run  <choose  due-extest>

Signed-off-by: Alex Doyle <alexddoyle@gmail.com>

diff --git a/libdue b/libdue
--- a/libdue
+++ b/libdue
@@ -813,6 +813,7 @@ function fxnDoExport()
     # Now export the saved image
     fxnPP "Saving selected image as [ ${exportImageName}.tar ]"
 	# Use the ID associated with the image
+	# Use 'save' rather than 'export' to save all layers.
 	#    fxnEC ${DOCKER_APP} save  $SELECTED_CONTAINER_ID > ${exportImageName}.tar
     fxnEC ${DOCKER_APP} save  $SELECTED_CONTAINER_ID -o ${exportImageName}.tar	foo:bar
 
@@ -845,14 +846,15 @@ function fxnDoImport()
 
     fxnPP "Importing [ $fileName ] as [ $dueName ]"
 
-    #tar -c "$fileName"  | docker image import - "$dueName"
-	#${DOCKER_APP} load --input $fileName myFoo
-	${DOCKER_APP} import $fileName $dueName
-#    ${DOCKER_APP} pull $fileName	
-    if [ $? != 0 ];then
-        fxnERR "Failed to import $fileName. Exiting."
-        exit 1
-    fi
+	#
+	# Use 'load' as it goes with 'save' - gathering all layers
+	# Do not mix 'import' and 'export' with 'load' and 'save'
+	# The former do not preserve all filesystem layers, and
+	# mixing the two creates failures that only show at run time.
+	# 
+	fxnEC ${DOCKER_APP} load --input $fileName  || exit 1
+	#tar -c "$fileName"  | docker image import - "$dueName"	
+	#${DOCKER_APP} import $fileName $dueName
     # Show the user the result
     ${DOCKER_APP} images | sed -e 's/^[ \t]*//g' | grep "$dueName"
 
