libdue - Reorder --login commands to print accurately
If --login is used to log in to a running container,
libdue now prints the actual command used for the log in,
as that could vary if the user was in a debug mode, or
on a Red Hat system.

Testing:
--------
Logged in to Fedora 33 and Debian contianers using Podman and
Docker, using an account in the container (--user-name) , and
had DUE create my account on the fly.
Also tested running commands like:
 ./due --run --command cd /bin \; ls -l

Signed-off-by: Alex Doyle <adoyle@nvidia.com>

diff --git a/libdue b/libdue
--- a/libdue
+++ b/libdue
@@ -262,7 +262,7 @@ function fxnDeleteImage()
 {
     if [ "$DELETE_TERM" = "" ];then
         echo "Existing images"
-        ${DOCKER_APP} images | sed -e 's/^[ \t]*//g' 
+        ${DOCKER_APP} images | sed -e 's/^[ \t]*//g'
         echo ""
         echo "Pass a string to wildcard delete."
     fi
@@ -275,9 +275,9 @@ function fxnDeleteImage()
         | grep "$DELETE_TERM" \
         | awk '{printf "# Delete: %s Tag: %s Image ID %s, Created %s %s %s, Size %s \n REPLACE_DOCKER_APP rmi --force %s \n", $1, $2, $3, $4, $5, $6, $7, $3}' \
               >> "$DELETE_SCRIPT"
-	# Set the applicatio 
-	sed -i "s/REPLACE_DOCKER_APP/$DOCKER_APP/g" "$DELETE_SCRIPT"
-	
+    # Set the applicatio
+    sed -i "s/REPLACE_DOCKER_APP/$DOCKER_APP/g" "$DELETE_SCRIPT"
+
     echo " ________________________________________________________________________"
     echo "|                                                                       "
     echo "| Run [ ./$DELETE_SCRIPT ]                                "
@@ -489,9 +489,9 @@ function fxnMakeNewDockerImage()
     local imageFrom="$1"
     local imageName="$2"
 
-	# Store the build command to be run, so it can be printed out to the user
-	local dockerBuildCommand=""
-	
+    # Store the build command to be run, so it can be printed out to the user
+    local dockerBuildCommand=""
+
     if [ "$2" = "" ];then
         # 3rd argument is optional
         fxnERR "Failed to pass enough arguments to fxnMakeNewDockerImage(). Exiting."
@@ -703,9 +703,9 @@ function fxnMakeNewDockerImage()
             # Create it all in one shot
             fxnHeader "Creating the new image with: $0 --create --build-dir ${BUILD_MERGE_DIR}/$imageName"
             $0 --create \
-			   --build-dir "${BUILD_MERGE_DIR}/$imageName" \
-			   --tag "$DOCKER_IMAGE_TAG" \
-			   --dockerarg "$DOCKER_SPECIFIC_BUILD_ARGS"
+               --build-dir "${BUILD_MERGE_DIR}/$imageName" \
+               --tag "$DOCKER_IMAGE_TAG" \
+               --dockerarg "$DOCKER_SPECIFIC_BUILD_ARGS"
         else
             fxnHeader " To create the new image, run: $0 --create --build-dir ${BUILD_MERGE_DIR}/$imageName"
         fi
@@ -735,34 +735,34 @@ function fxnMakeNewDockerImage()
         # if this doesn't exist at this point, things have gone very wrong.
         fxnEC cd "${BUILD_MERGE_DIR}/$imageName" || exit 1
 
-		# Sanity check the code doing most of the work
-		# Podman/Docker should return success
-		DockerAppPath=$( which $DOCKER_APP )
-		if [ "$DockerAppPath" = "" ];then
-			fxnERR "Failed to find path for [ $DOCKER_APP ]. Is it installed?"
-			exit 1
-		fi
-		if [ "$DOCKER_APP" = 'docker' ];then
-			# Check if the Docker daemon is running.
-			if [ ! -e /var/run/docker.sock ];then
-				fxnERR "Is Docker running?"
-				exit 1
-			fi
-		fi
+        # Sanity check the code doing most of the work
+        # Podman/Docker should return success
+        DockerAppPath=$( which $DOCKER_APP )
+        if [ "$DockerAppPath" = "" ];then
+            fxnERR "Failed to find path for [ $DOCKER_APP ]. Is it installed?"
+            exit 1
+        fi
+        if [ "$DOCKER_APP" = 'docker' ];then
+            # Check if the Docker daemon is running.
+            if [ ! -e /var/run/docker.sock ];then
+                fxnERR "Is Docker running?"
+                exit 1
+            fi
+        fi
 
         #
         # Create the image based off the contents of ./$imageName
         # This allows the user to test incremental changes without starting from scratch.
-		dockerBuildCommand="${DOCKER_APP} build \
-			  --no-cache=true \
-			  $DOCKER_SPECIFIC_BUILD_ARGS \
-			  --tag "${CONFIGURED_NAME_AND_TAG}" \
-			  --file=./Dockerfile.create \
-			  ."
-		# Print the build command, turning all whitespace in to one space.
-		fxnHeader "Building with: $( echo $dockerBuildCommand | sed -e 's/[[:space:]]\+/ /g')"
+        dockerBuildCommand="${DOCKER_APP} build \
+              --no-cache=true \
+              $DOCKER_SPECIFIC_BUILD_ARGS \
+              --tag "${CONFIGURED_NAME_AND_TAG}" \
+              --file=./Dockerfile.create \
+              ."
+        # Print the build command, turning all whitespace in to one space.
+        fxnHeader "Building with: $( echo $dockerBuildCommand | sed -e 's/[[:space:]]\+/ /g')"
 
-		# Run it.
+        # Run it.
         fxnEC $dockerBuildCommand ||  exit 1
     fi
 
@@ -825,10 +825,10 @@ function fxnDoExport()
     fxnSelectContainer "export" $exportFilter
 
     # fxnSelectContainer will have set this.
-	# If the name has a / in it, replace that with a -
-	# Podman names do this, and we don't want it interpreted
-	#  as a subdirectory.
-    exportImageName="${SELECTED_CONTAINER_NAME//\//-}"	
+    # If the name has a / in it, replace that with a -
+    # Podman names do this, and we don't want it interpreted
+    #  as a subdirectory.
+    exportImageName="${SELECTED_CONTAINER_NAME//\//-}"
 
     # check for file overwrite
     if [ -e ${exportImageName}.tar ];then
@@ -838,10 +838,10 @@ function fxnDoExport()
 
     # Now export the saved image
     fxnPP "Saving selected image as [ ${exportImageName}.tar ]"
-	# Use the ID associated with the image
-	# Use 'save' rather than 'export' to save all layers.
-	#    fxnEC ${DOCKER_APP} save  $SELECTED_CONTAINER_ID > ${exportImageName}.tar
-    fxnEC ${DOCKER_APP} save  $SELECTED_CONTAINER_ID -o ${exportImageName}.tar 
+    # Use the ID associated with the image
+    # Use 'save' rather than 'export' to save all layers.
+    #    fxnEC ${DOCKER_APP} save  $SELECTED_CONTAINER_ID > ${exportImageName}.tar
+    fxnEC ${DOCKER_APP} save  $SELECTED_CONTAINER_ID -o ${exportImageName}.tar
 
     fxnPP "Exported container is in $(pwd) "
     ls -l | grep  ${exportImageName}.tar
@@ -872,15 +872,15 @@ function fxnDoImport()
 
     fxnPP "Importing [ $fileName ] as [ $dueName ]"
 
-	#
-	# Use 'load' as it goes with 'save' - gathering all layers
-	# Do not mix 'import' and 'export' with 'load' and 'save'
-	# The former do not preserve all filesystem layers, and
-	# mixing the two creates failures that only show at run time.
-	# 
-	fxnEC ${DOCKER_APP} load --input $fileName  || exit 1
-	#tar -c "$fileName"  | docker image import - "$dueName"	
-	#${DOCKER_APP} import $fileName $dueName
+    #
+    # Use 'load' as it goes with 'save' - gathering all layers
+    # Do not mix 'import' and 'export' with 'load' and 'save'
+    # The former do not preserve all filesystem layers, and
+    # mixing the two creates failures that only show at run time.
+    #
+    fxnEC ${DOCKER_APP} load --input $fileName  || exit 1
+    #tar -c "$fileName"  | docker image import - "$dueName"
+    #${DOCKER_APP} import $fileName $dueName
     # Show the user the result
     ${DOCKER_APP} images | sed -e 's/^[ \t]*//g' | grep "$dueName"
 
@@ -1018,7 +1018,7 @@ function fxnSelectContainer()
         #
         # Run a container
         #
-		# Podman will add leading spaces that throw off start-of-line pattern matching. Trim them.
+        # Podman will add leading spaces that throw off start-of-line pattern matching. Trim them.
         theContainers=$( ${DOCKER_APP} images --format 'table  {{.Repository}}\t{{.Tag}}\t{{.Size}}\t{{.ID}}' | sed -e 's/^[ \t]*//g' )
         if [ $? != 0 ];then
             # As this is frequently the first access of the system's Docker daemon,
@@ -1072,11 +1072,11 @@ function fxnSelectContainer()
         #
         # select existing container
         #
-		# Podman doesn't print the header returning from a query. 
-		if [ "${DOCKER_APP}" = "podman" ];then
-			theContainers="NAMES              IMAGE    CONTAINER ID  COMMAND 
+        # Podman doesn't print the header returning from a query.
+        if [ "${DOCKER_APP}" = "podman" ];then
+            theContainers="NAMES              IMAGE    CONTAINER ID  COMMAND
 "
-		fi
+        fi
 
         if [ "$VERBOSITY_LEVEL" -ne 0 ];then
             theContainers+=$(     ${DOCKER_APP} ps --format 'table {{.Names}}\t{{.Image}}\t{{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Command}}')
@@ -1105,8 +1105,8 @@ function fxnSelectContainer()
     fi
 
 
-	# separate the head from the body to prevent it getting numbered		
-	theHeader=$( echo "$theContainers" | head -n 1 )
+    # separate the head from the body to prevent it getting numbered
+    theHeader=$( echo "$theContainers" | head -n 1 )
 
     # set -n - clip first line
     # cat -n - put a number at the start
@@ -1176,8 +1176,8 @@ function fxnSelectContainer()
         # This should be whats left from a filter operation
         ENTRY=1
     fi
-	
-	# If dealing with image files, starting them or exporting them...
+
+    # If dealing with image files, starting them or exporting them...
     if [ "$doOperation" = "start" ] || [ "$doOperation" = "export" ];then
         # use the pre-filtered var, theBody
 
@@ -1281,8 +1281,8 @@ function fxnDoLogin()
 
     if [ "$1" = "start" ];then
         # If we are selecting an image to run as a container
-		#        DUEImageType=$( ${DOCKER_APP} inspect -f '{{.Config.Labels.DUEImageType}}' "${SELECTED_CONTAINER_NAME}":"${SELECTED_CONTAINER_TAG}" )
-		DUEImageType=$( ${DOCKER_APP} inspect -f '{{.Config.Labels.DUEImageType}}' "${SELECTED_CONTAINER_NAME}":"${SELECTED_CONTAINER_TAG}" )
+        #        DUEImageType=$( ${DOCKER_APP} inspect -f '{{.Config.Labels.DUEImageType}}' "${SELECTED_CONTAINER_NAME}":"${SELECTED_CONTAINER_TAG}" )
+        DUEImageType=$( ${DOCKER_APP} inspect -f '{{.Config.Labels.DUEImageType}}' "${SELECTED_CONTAINER_NAME}":"${SELECTED_CONTAINER_TAG}" )
     else
         # Logging in to an already running container
         DUEImageType=$( ${DOCKER_APP} container inspect -f '{{.Config.Labels.DUEImageType}}' "${SELECTED_CONTAINER_ID}")
@@ -1380,7 +1380,7 @@ function fxnDoLogin()
             executeProgram+=" --docker-group-id $dockerGID "
 
             # specify user and ID
-			executeProgram+=" --username $USER_NAME --userid $USER_ID --groupid $USER_GROUP_ID --groupname $USER_GROUP_NAME "
+            executeProgram+=" --username $USER_NAME --userid $USER_ID --groupid $USER_GROUP_ID --groupname $USER_GROUP_NAME "
 
 
             # Set any CONTAINER_SPECIFIC_ARGS
@@ -1405,7 +1405,7 @@ function fxnDoLogin()
         # Local file systems the container can mount.
         #
         if [ "$USE_HOMEDIR" = "" ];then
-			HOMEDIR_PATH+=" $(realpath ~/):/home/$USER_NAME"
+            HOMEDIR_PATH+=" $(realpath ~/):/home/$USER_NAME"
         else
             echo "$USE_HOMEDIR" | grep -q "/"
             if [ $? = 0 ];then
@@ -1414,31 +1414,31 @@ function fxnDoLogin()
             # not having an absolute path = use container home dir.
         fi
 
-		# Add the homedir to mount
-		ADDITIONAL_MOUNTS+=" --volume $HOMEDIR_PATH"
+        # Add the homedir to mount
+        ADDITIONAL_MOUNTS+=" --volume $HOMEDIR_PATH"
         if [ "$CURRENT_WORKING_DIRECTORY" != "" ];then
 
-			if [[ "$CURRENT_WORKING_DIRECTORY" != "$USE_HOMEDIR"* ]];then
-				# Let this fall through and get caught in the duplicate check, which has verbose
-				# solutions.
-			    echo "Warning: Current working directory [ $CURRENT_WORKING_DIRECTORY ]"
-				echo " is not under home directory [ $USE_HOMEDIR ]."
-				echo " Use --mount-dir or --home-dir options to resolve paths if needed."
-			fi
+            if [[ "$CURRENT_WORKING_DIRECTORY" != "$USE_HOMEDIR"* ]];then
+                # Let this fall through and get caught in the duplicate check, which has verbose
+                # solutions.
+                echo "Warning: Current working directory [ $CURRENT_WORKING_DIRECTORY ]"
+                echo " is not under home directory [ $USE_HOMEDIR ]."
+                echo " Use --mount-dir or --home-dir options to resolve paths if needed."
+            fi
 
-			# If cwd is the home directory, don't specify it as a volume mount again.
-			# Especially because --home-dir may have been used to specify a different home
-			# directory, and the launch will die trying to mount:
-			#  /foo:/home/usr
-			#   and
-			#  /bar:/home/usr
-			# at the same time...
-			if [[ "$MOUNT_CURRENT_WORKING_DIRECTORY" != "/home/$USER_NAME" ]];then
-				# If we are making the inside of the container have the
-				# same path as the directory this was invoked in, do it here.
-				ADDITIONAL_MOUNTS+=" --volume $MOUNT_CURRENT_WORKING_DIRECTORY:$MOUNT_CURRENT_WORKING_DIRECTORY"
-				# Put the user in the same equivalent directory in the container.
-			fi
+            # If cwd is the home directory, don't specify it as a volume mount again.
+            # Especially because --home-dir may have been used to specify a different home
+            # directory, and the launch will die trying to mount:
+            #  /foo:/home/usr
+            #   and
+            #  /bar:/home/usr
+            # at the same time...
+            if [[ "$MOUNT_CURRENT_WORKING_DIRECTORY" != "/home/$USER_NAME" ]];then
+                # If we are making the inside of the container have the
+                # same path as the directory this was invoked in, do it here.
+                ADDITIONAL_MOUNTS+=" --volume $MOUNT_CURRENT_WORKING_DIRECTORY:$MOUNT_CURRENT_WORKING_DIRECTORY"
+                # Put the user in the same equivalent directory in the container.
+            fi
             COMMAND_LIST=" cd $CURRENT_WORKING_DIRECTORY ; $COMMAND_LIST"
         fi
 
@@ -1459,7 +1459,7 @@ function fxnDoLogin()
             echo ""
             echo " Note: some containers (debian package builds) mount the host system above the current working directory."
             echo " Solutions:  Add a directory to change the path?"
-			echo "             Use --home-dir to specify a different host home directory to use in the container."
+            echo "             Use --home-dir to specify a different host home directory to use in the container."
             echo "             Move the current working directory elsewhere?"
             #
             # check for a redefine of the home directory and use of the original home directory.
@@ -1623,49 +1623,49 @@ function fxnDoLogin()
         echo " -------- Type 'exit' to leave.  Docker Container Output Follows ------------"
 
         echo ""
-
-		if [ "$DOCKER_APP" = "podman" ];then
-			APPLICATION_ARGS="  --userns=keep-id "
-		fi
+set -x
+        if [ "$DOCKER_APP" = "podman" ];then
+            APPLICATION_ARGS="  --userns=keep-id "
+        fi
         if [ "$cmdList" != "" ];then
             # even the empty "" here will trip up a shell login, but they are
             # needed if cmdList is set to anything. Hence two cases.
             ${DOCKER_APP} run $APPLICATION_ARGS $runCMD "$cmdList"
         else
-			${DOCKER_APP} run $APPLICATION_ARGS $runCMD "$cmdList"
+            ${DOCKER_APP} run $APPLICATION_ARGS $runCMD
         fi
 
     else
-
+        local LoginCommand=""
         if [ "$USER_NAME" != "" ];then
             userNameArg=" --user $USER_NAME "
+        fi
+
+        if [ "$DO_DEBUG" = "TRUE" ];then
+            # If this is debug, make few assumptions about the container's ability to handle
+            # logins. Just start a specified shell.
+            LoginCommand="${DOCKER_APP} exec $doInteractive  $userNameArg ${SELECTED_CONTAINER_ID} $LOGIN_SHELL"
+        else
+            if [ "$OS_TYPE" = "RedHat" ];then
+                LoginCommand="${DOCKER_APP} exec $doInteractive --user $USER_NAME  ${SELECTED_CONTAINER_ID} /bin/bash --login"
+            else
+                # Log into container as root, then set ID to user. This executes .bashrc configs and
+                # feels more like a real login.
+                LoginCommand="${DOCKER_APP} exec $doInteractive --user root ${SELECTED_CONTAINER_ID} /bin/login -p -f $USER_NAME"
+            fi
         fi
         echo "Logging in to running  [ $SELECTED_CONTAINER_ID ] with: "
         echo " ___________________________________________________________________________"
         echo "|"
-        echo "|  ${DOCKER_APP} exec $doInteractive $userNameArg ${SELECTED_CONTAINER_ID}  $LOGIN_SHELL"
+        echo "|  $LoginCommand"
         echo "|___________________________________________________________________________"
-        echo ""
         echo ""
         echo " ---------------------------------------------------------------------------"
         echo " -             Logging in to container. Type 'exit' to leave.              -"
         echo " ------------------- Docker Container Output Follows -----------------------"
         # all output from here on down is from the container session, rather than the
         # launch from DUE
-
-        if [ "$DO_DEBUG" = "TRUE" ];then
-            # If this is debug, make few assumptions about the container's ability to handle
-            # logins. Just start a specified shell.
-            ${DOCKER_APP} exec $doInteractive  $userNameArg "${SELECTED_CONTAINER_ID}" $LOGIN_SHELL
-        else
-            if [ "$OS_TYPE" = "RedHat" ];then
-                ${DOCKER_APP} exec $doInteractive --user "$USER_NAME"  "${SELECTED_CONTAINER_ID}" /bin/bash --login
-            else
-                # Log into container as root, then set ID to user. This executes .bashrc configs and
-                # feels more like a real login.
-                ${DOCKER_APP} exec $doInteractive --user root "${SELECTED_CONTAINER_ID}" /bin/login -p -f "$USER_NAME"
-            fi
-        fi
+        $LoginCommand
     fi
     # User typed 'exit' or something blew up?
     return $?
@@ -1934,7 +1934,7 @@ function fxnDoContainerStop()
         echo "Stopped."
     else
 
-        header=$( ${DOCKER_APP} ps | head -n 1 ) 
+        header=$( ${DOCKER_APP} ps | head -n 1 )
         terms=$( ${DOCKER_APP} ps | grep "$stopTerm" )
         if [ "$filterByUser" != "" ];then
             terms=$( echo "$terms" | grep "$filterByUser" )
@@ -1951,8 +1951,8 @@ function fxnDoContainerStop()
         # put a # after the container ID to turn the rest of the info in to a comment
         # prepend the ID with 'docker stop' to create an executable command.
         #echo "$terms" | sed -e 's/   / # /' | sed -e 's/^/docker stop /g' >> $STOP_SCRIPT
-		toDelete=$( echo "$terms" | sed -e 's/ / # /' | sed -e "s/^/${DOCKER_APP} stop /g" )
-		#        toDelete=$( echo "$terms" | sed -e 's/   / # /' | sed -e "s/^/${DOCKER_APP} stop /g" )
+        toDelete=$( echo "$terms" | sed -e 's/ / # /' | sed -e "s/^/${DOCKER_APP} stop /g" )
+        #        toDelete=$( echo "$terms" | sed -e 's/   / # /' | sed -e "s/^/${DOCKER_APP} stop /g" )
 
         # Create the stop script to be very explicit about what will happen
         {
