--use-local-repo adds initial support for a local Debian package repository.
This is helpful when building packages that depend on other
packages to have already been built.

Example - if package B depends on files supplied by package A
 cd package A dir
 duebuild --use-local-repo myRepo --cbuild
 (puts package A debs in myRepo)
 cd package B dir
 ( pulls package A debs from myRepo)
 duebuild --use-local-repo myRepo --cbuild
 (puts package B debs in myRepo)

In addition to creating the repository, the script:
1 puts an entry under /etc/apt/sources.list.d so that
  the build container will reference the repository.
2 Adds an /etc/apt/preferences.d file to set the local
  repository to have a higher priority than anything else.
  This assumes that, given a choice between a package
  coming from upstream, or what was built and put in the
  local repository, the local repository wins.

As the repository is created one directory level above the
build area, but DUE is smart enough to mount build containers
one directory up, the repository should persist on the host
system, and be available for subsequent invocations.

Note: only tested so far with amd64 and debs.
Adding source or multiple architectures should be tested
when a test case is available.

diff --git a/templates/debian-package/filesystem/usr/local/bin/duebuild b/templates/debian-package/filesystem/usr/local/bin/duebuild
--- a/templates/debian-package/filesystem/usr/local/bin/duebuild
+++ b/templates/debian-package/filesystem/usr/local/bin/duebuild
@@ -111,6 +111,7 @@ function fxnHelp()
 
     echo "   --prebuild-script <scr>     Run script at container path <scr> before starting build. Pass 'NONE' to ignore."
     echo "   --add-sources-list <file>   Container relative path to include sources.list in build dir."
+    echo "   --use-local-repo <repo>     Create a local package repository named <repo> to store and serve packages."
     echo "   --version                   Print version"
     echo "   --script-debug              Enable -x if passed as first argument."
 
@@ -155,6 +156,10 @@ function fxnHelpExamples()
     echo ""
     echo "  Insert a string into the version"
     echo "   $0 --cbuild --dev-version ~1234"
+	echo ""
+	echo "  Store build products in a repository for future builds"
+	echo "  (i.e. building things that need other things built to build...)"
+	echo "   $0 --cbuild --use-local-repo myLocalRepo "
     echo ""
 }
 
@@ -248,7 +253,7 @@ function fxnDebianSourceOne()
     # packageName should be the base name of the package ( no versions )
     #
     if [ ! -e ~/.git ];then
-        fxnWarn "No .git directory found to remove. Skipping --source-format-one."
+        fxnWARN "No .git directory found to remove. Skipping --source-format-one."
     fi
 
     # And make sure there's a format file before we start cleaning house.
@@ -355,6 +360,153 @@ function fxnIsolatePackageDependencies()
     return $?
 }
 
+# Takes: name to use for repository
+#        Debian package  architecture ( or 'default' to determine it from the system.)
+#        absolute path to a directory that contains files to add to the repository
+
+# Does:  Creates a local package repsoitory one directory up from
+#        the current build directory (or uses it if it already exists)
+#        and adds it to the build.
+function fxnUseLocalPackageRepository()
+{
+  local repoName="$1"
+    local useArchitecture="$2"
+    local addContentsDir="$3"  
+
+    local repositoryDistribution="local-due-repo"
+    local repositoryComponent="main"
+    local sourcesListFile="local-build-repo.list"
+    local aptPreferencesFile="/etc/apt/preferences.d/10local-build-repo"
+    local poolDir
+    local debsDir
+
+	if [ "$useArchitecture" = "default" ];then
+		# Use target arch as that represents the end build product.
+		useArchitecture=$( dpkg-architecture --query DEB_TARGET_ARCH )
+	fi
+       
+    LOCAL_PACKAGE_REPOSITORY_PATH=$( realpath "${BUILD_DIR}/.." )
+    echo "Using path $LOCAL_PACKAGE_REPOSITORY_PATH"
+
+    LOCAL_PACKAGE_REPOSITORY_DIR=$( realpath "${BUILD_DIR}/.." )
+    echo "Using path $LOCAL_PACKAGE_REPOSITORY_DIR"
+    LOCAL_PACKAGE_REPOSITORY_ROOT="${LOCAL_PACKAGE_REPOSITORY_DIR}/${repoName}"
+
+    poolDir="${LOCAL_PACKAGE_REPOSITORY_ROOT}/pool"
+    debsDir="${LOCAL_PACKAGE_REPOSITORY_ROOT}/debs"
+    
+    # Location of binary specific section within the local repo
+    repositoryBinDir=${LOCAL_PACKAGE_REPOSITORY_ROOT}/dists/${repositoryDistribution}/${repositoryComponent}/binary-${useArchitecture}
+    
+    
+    if [ ! -e "$LOCAL_PACKAGE_REPOSITORY_ROOT" ];then
+	fxnPP "Creating directories for local Debian package repository at: $LOCAL_PACKAGE_REPOSITORY_PATH"	
+	fxnEC mkdir "$LOCAL_PACKAGE_REPOSITORY_ROOT" || exit 1
+	fxnPP "Creating $debsDir"
+	fxnEC mkdir "$debsDir" || exit 1
+	fxnPP "Creating $poolDir"	
+	fxnEC mkdir "$poolDir" || exit 1
+	fxnPP "Creating $repositoryBinDir"	
+	fxnEC mkdir -p "$repositoryBinDir" || exit 1
+    else
+	# add contents may be empty in the case of the repository getting created,
+		# or if this call was to just update the sources.list
+		if [ "$addContentsDir" != "" ];then
+			# only update if there is stuff to update.
+			if [ ! -e "$addContentsDir" ];then
+				fxnERR "Failed to find directory of debs to add at [ $addContentsDir ]. NOT modifiying local repository."
+				exit 1
+			fi
+			
+			fxnPP "Local package repository already exists at: $LOCAL_PACKAGE_REPOSITORY_PATH"
+			# If this is an initialization, Packages won't exist as the repository is empty	    
+			if [ -e "${repositoryBinDir}/Packages" ];then
+				# Otherwise clean them out to get updated
+				fxnPP "Removing Package index files before update."
+				fxnEC rm "${repositoryBinDir}/Packages"    || exit 1
+				fxnEC rm "${repositoryBinDir}/Packages.gz" || exit 1
+			fi
+		fi
+    fi
+
+    # if there are any *.debs in this directory, add them.
+    # TODO: add source
+
+    if [ "$addContentsDir" != "" ];then    
+	fxnPP "Copying *.deb from $addContentsDir to $poolDir"
+	fxnEC cp -f "$addContentsDir"/*.deb "$poolDir" || exit 1
+	curDir=$(pwd)
+
+	cd "$LOCAL_PACKAGE_REPOSITORY_ROOT"
+
+	fxnPP "Updating local repository at $LOCAL_PACKAGE_REPOSITORY_PATH"
+	#	fxnEC apt-ftparchive --arch $useArchitecture  packages pool | 
+	fxnEC apt-ftparchive packages pool | \
+	    tee ${repositoryBinDir}/Packages | \
+	    gzip > ${repositoryBinDir}/Packages.gz  || exit 1
+
+	# Options to supply to the release file
+	optionList=" -o APT::FTPArchive::Release::Origin=DUE-duebuild \
+-o APT::FTPArchive::Release::Label=localPackageRepository \
+-o APT::FTPArchive::Release::Suite=local-repo \
+-o APT::FTPArchive::Release::Version=1.0 \
+-o APT::FTPArchive::Release::Codename=local-due-repo \
+-o APT::FTPArchive::Release::Architectures=$useArchitecture \
+-o APT::FTPArchive::Release::Description=LocalPackageRepository \
+-o APT::FTPArchive::Release::Components=main"
+
+	# release under dists/local-due-repo/main/binary-amd64
+	fxnPP "Creating Release file under ${repositoryBinDir}"
+	apt-ftparchive release ${repositoryBinDir} > \
+				   ${repositoryBinDir}/Release
+	
+	# Top level release file under dists/local-due-repo
+	fxnPP "Creating Release file under ${LOCAL_PACKAGE_REPOSITORY_ROOT}/dists/${repositoryDistribution}"
+	apt-ftparchive $optionList release ${LOCAL_PACKAGE_REPOSITORY_ROOT}/dists/${repositoryDistribution}/ > \
+				   ${LOCAL_PACKAGE_REPOSITORY_ROOT}/dists/${repositoryDistribution}/Release
+
+	cd "$curDir"
+    fi # if contents to add
+
+    # Update the sources.list file
+    localRepoSourcesList="${LOCAL_PACKAGE_REPOSITORY_ROOT}/${sourcesListFile}"
+    if [ ! -e /etc/apt/sources.list.d/${sourcesListFile} ];then
+		fxnPP "Creating sources.list file for local repository as: [ $localRepoSourcesList ]"
+
+		echo "# Created by $(whoami) using $0 building from $(pwd) on $(date)" > $localRepoSourcesList
+		echo "deb [arch=$useArchitecture trusted=yes] copy:${LOCAL_PACKAGE_REPOSITORY_ROOT}/ $repositoryDistribution $repositoryComponent" >> $localRepoSourcesList    
+
+		fxnPP "Adding local repository sources.list to local /etc/apt/sources.list.d"
+		fxnEC sudo cp $localRepoSourcesList /etc/apt/sources.list.d/ || exit 1
+    else
+		fxnPP "Local sources.list exists at /etc/apt/sources.list.d/${sourcesListFile}"
+    fi # If no local sources list file
+
+    
+    # Pin the local packages to a higher than normal priority
+	# View with: apt-cache policy
+	# If making changes, force a refresh as follows:
+	#   remove the entry under /etc/apt/sources.list.d/
+	#   apt-get update
+	#   restore the entry under /etc/apt/sources.list.d/
+    if [ ! -e "$aptPreferencesFile" ];then
+		fxnPP "Setting local repository priority high with: $aptPreferencesFile"
+		# Note that this only works if there is a Release file in the repo
+cat <<EOF > /tmp/apt-pref 
+# Created by $(whoami) using $0 building from $(pwd) on $(date)
+Package: *
+Pin: release n=local-due-repo
+Pin-Priority: 990  > 
+EOF
+	fxnEC sudo mv /tmp/apt-pref "$aptPreferencesFile" || exit 1
+    else
+	fxnPP "Local repository has high priority with add of $aptPreferencesFile"
+    fi
+
+    fxnPP "Updating..."
+    sudo apt-get update
+
+}
 
 # Function to replace sbuild
 function fxnDoDebianBuild()
@@ -375,7 +527,10 @@ function fxnDoDebianBuild()
 
 	# Always apt-get update
     fxnPP "Running apt-get update."
-    sudo apt-get update || fxnWarn "apt-get update failed. Continuing with local index."
+	if [ "$LOCAL_REPO_NAME" != "" ];then
+		echo "Ignore 'Failed to stat' errors if there are no packages in local repository $LOCAL_REPO_NAME"
+	fi
+    sudo apt-get update || fxnWARN "apt-get update failed. Continuing with local index."
 
 
     # Make sure the environment has the tools to configure the environment.
@@ -466,6 +621,11 @@ function fxnDoDebianBuild()
     # use grep to avoid errors when no .debs found
     ls -lrt ../ | grep ".deb"  | sed -e "s/^/${MSG_SPACER}/g"
 
+    # if packages are being stored in a local repository
+    if [ "$LOCAL_REPO_NAME" != "" ];then
+	fxnPP "Adding built debs to local repository [ $LOCAL_REPO_NAME ]"
+	fxnUseLocalPackageRepository "$LOCAL_REPO_NAME" "default" "$(realpath ../)"
+    fi
     echo ""
 }
 
@@ -663,6 +823,16 @@ do
             shift
             ;;
 
+	--use-local-repo )
+	    # Use (or create if it does not exist) a local Debian
+	    # package repository to hold build products, and serve
+	    # them for subsequent builds.
+	    # Useful when building packages that depend on previously
+	    # built packages.
+	    LOCAL_REPO_NAME="$2"
+	    shift
+	    ;;
+		
         -c | --cbuild )
             # Default to build everything in container context
             DO_BUILD="TRUE"
@@ -706,10 +876,7 @@ do
                 fxnERR " --build-from-deb-source file [ $BUILD_SOURCE_DSC_FILE ] does not end in .dsc. Exiting."
                 exit 1
             fi
-
             shift
-
-
             ;;
 
         -j* )
@@ -864,6 +1031,15 @@ fi
 # Add parallel build
 if [ "$BUILD_JOBS" != "" ];then
     BUILD_ARGS+=" -j${BUILD_JOBS} "
+fi
+
+# use/create local repository to store build products.
+# Process this before adding sources list, as this repository
+# will be searched as well.
+if [ "$LOCAL_REPO_NAME" != "" ];then
+	# Leave last parameter out as there are no packages, but
+	# the repository references should be added.
+	fxnUseLocalPackageRepository "$LOCAL_REPO_NAME" "default"
 fi
 
 if [ "$ADD_SOURCES_LIST" != "" ];then
