Upgrade due-manage-local-repo.sh
duebuild-readme.md
- Note that local repos must be either under the user's home dir,
or explicitly added as a host mount when the container is invoked

duebuild
- multiple sources.list files can be added (though keys
  may be an issue)

due-manage-local-repo.sh
 Allow add of multiple debs or dirs
 Updated examples
 Local repository enable removes all references to a prior
  repository when it is enabled, avoiding collisions.
 Re-arranged apt update calls so that builds can start with an empty
 repository to be filled with packages and not error out

due-manage-local-repo.sh
- Updated examples
- Disable apt-get update if the repository has been created
  but package add is pending the end of the current build.
  This will keep it from apt-get erroring out when it accesses a
  repository with no packages.

- When --enable-repo is passed to the due-manage-local-repo.sh,
  always delete the previous configuraton and write the new one clean.
  This should allow for specifying different repositories in the
  container, although only one will be active at a time.

- Support multiple individual debs to be speciified on an add.
  Ex ./due-manage-local-repo.sh --name myRepo --add foo.deb --add bar.deb

- Support multiple sources.list files
  --add-sources-list accepts a sources.list
  file for every use of the argument, so:
   --add-sources-list foo.list --add-sources-list bar.list
  ..will add foo.list and bar.list to /etc/apt/sources.list.d/

  Cases for using this would be during prototyping where a
  developer would want to largely use their default upstream repository
  but pull packages from sid, and use a local repository to
  store build products.
  --add-sources-list sid.list --use-local-repo myrepo
 ...would accomplish this.

It might not be a common scenario, but it is obnoxious when hit.

- Move the addtion of the sources.list for any local
  repositories to be the last apt-get update before build, since
  a newly added empty repository will throw errors on an apt get.
  (The assumption here is that the empty repository will get
  populated with what is being built.)

- Add an apt update after a local repository has packages added,
  which allows single line initializations like this to work:

~/due-manage-local-repo.sh --name refrepo --create-repo \
  --add /home/adoyle/debian-signing-test-debs/ --enable-repo

  ...where local repo refrepo gets created, has the debs under
   debian-signing-test-debs added to it, and is apt updated.

Signed-off-by: Alex Doyle <adoyle@nvidia.com>

diff --git a/templates/debian-package/filesystem/usr/local/bin/duebuild b/templates/debian-package/filesystem/usr/local/bin/duebuild
--- a/templates/debian-package/filesystem/usr/local/bin/duebuild
+++ b/templates/debian-package/filesystem/usr/local/bin/duebuild
@@ -2,6 +2,7 @@
 # SCRIPT_PURPOSE: Low-rent version of sbuild. Resolve dependencies. Build a debian package, and maybe more
 # DUE_VERSION_COMPATIBILITY_TRACKING=1.0.0
 
+# Copyright 2021 NVIDIA Corporation.  All rights reserved.
 # Copyright 2019,2020 Cumulus Networks, Inc.  All rights reserved.
 #
 #  SPDX-License-Identifier:     MIT
@@ -820,11 +821,12 @@ do
             ;;
 
         --add-sources-list )
-            ADD_SOURCES_LIST="$2"
-            if [ ! -e "$ADD_SOURCES_LIST" ];then
-                fxnERR "Container failed to find additional sources.list file [ $ADD_SOURCES_LIST ]. Exiting."
+            if [ ! -e "$2" ];then
+                fxnERR "Container failed to find additional sources.list file [ $2 ]. Exiting."
                 exit 1
             fi
+            # Allow stacking multiple sources.list files to copy in.
+            ADD_SOURCES_LIST+=" $2 "
             shift
             ;;
 
@@ -1098,21 +1100,26 @@ if [ "$BUILD_JOBS" != "" ];then
     BUILD_ARGS+=" -j${BUILD_JOBS} "
 fi
 
-# use/create local repository to store build products.
-# Process this before adding sources list, as this repository
-# will be searched as well.
+# Add sources.list files and apt-update BEFORE using a local
+# package repository. If the local repo was just created and
+# is empty, it throws errors on apt-get update.
+if [ "$ADD_SOURCES_LIST" != "" ];then
+    for srcfile in $ADD_SOURCES_LIST ; do
+        fxnPP "Copying $srcfile to /etc/apt/sources.list.d"
+        fxnEC sudo cp "$srcfile" /etc/apt/sources.list.d  || exit 1
+    done
+    # If any added sources.list file is bad, fail immediately.
+    fxnEC sudo apt-get update || exit 1
+
+fi
+
+# Use/create local repository to store build products.
+# May be empty at start, expecting build products to be added.
+# NOTE: it will cause errors if apt-get is run while it is empty.
 if [ "$LOCAL_REPO_NAME" != "" ];then
     # Leave last parameter out as there are no packages, but
     # the repository references should be added.
     fxnUseLocalPackageRepository "$LOCAL_REPO_NAME" "default"
-fi
-
-if [ "$ADD_SOURCES_LIST" != "" ];then
-    fxnPP "Copying $ADD_SOURCES_LIST to /etc/apt/sources.list.d"
-    fxnEC sudo cp "$ADD_SOURCES_LIST" /etc/apt/sources.list.d  || exit 1
-    # If the added sources.list is bad, fail immediately.
-    fxnEC sudo apt-get update || exit 1
-
 fi
 
 
