If --add-sources-list file has bad info for Debian package duebuild, fail immediately.

diff --git a/templates/debian-package/filesystem/usr/local/bin/duebuild b/templates/debian-package/filesystem/usr/local/bin/duebuild
--- a/templates/debian-package/filesystem/usr/local/bin/duebuild
+++ b/templates/debian-package/filesystem/usr/local/bin/duebuild
@@ -863,7 +863,10 @@ fi
 
 if [ "$ADD_SOURCES_LIST" != "" ];then
     fxnPP "Copying $ADD_SOURCES_LIST to /etc/apt/sources.list.d"
-    sudo cp "$ADD_SOURCES_LIST" /etc/apt/sources.list.d
+    fxnEC sudo cp "$ADD_SOURCES_LIST" /etc/apt/sources.list.d  || exit 1
+	# If the added sources.list is bad, fail immediately.
+	fxnEC sudo apt-get update || exit 1
+	
 fi
 
 
