Support older (Debian 8) releases.
fixes #41

When using a Docker image for a release that is no longer
supported, users will encounter problems around expired keys
(resulting in validation errors) and possibly missing
upstream package repositories.

Fixing the missing repository problem will require the
developer to find archived copies of the repository and update
the image's /etc/apt/sources.list configuration.
However, DUE can help mitigate the key expiration/validation
issues by disabling APT security checks, reasoning that a
failed install at this point is worse than not having an image at all.
To that end, DUE's `pre-install-config.sh.template` will
`apt --force-install` packages for Debian releases.
The `post-install-config.sh` script will check against distributions
known to have these problems, and will notify the user with a warning
during image creation.
To do this, the `post-install-config.sh` will source the image's
`/etc/os-release` file and run APT commands with `faketime` to make
the system think the keys have not yet expired, provided the container's
release version matches a known release that has this problem.
As of 01/02/23, Debian 8 (Jessie) is the only image that is supported this way.

Additionally, the Debian `duebuild` script supports building in
containers that have this problem by supplying the `--force-apt` option.
Ex: `duebuild --force-apt --build`
will disable the checks on pulling in build dependencies, and do its
best to just build.

Users can also try force updating the keys by adding
`sudo apt-key adv --recv-keys` to the `pre-install-config.sh.template`
and re-creating the image, but this may result in getting a
newer set of expired keys.

Testing
-------
Built:
 debian-package:
  image from Debian 8 Jessie,
    ...and used it to build watchdog package with:
    duebuild --force-apt --cbuild
  images from Debian 11 Bullseye, and Sid
    ...and used them to build watchdog package with:
    duebuild --cbuild
  Also tried the Debian 11 watchdog build on WSL.

 onie:
  image from Debian 8 jessie
    ...and used it to build accton_as6701_32x from the
    2020.11 legacy branch with
     make MACHINEROOT=../machine/accton \
       MACHINE=accton_as6701_32x -j8 all demo

  image from Debian 10 Buster
    ...and used it to biuld a secure boot virtual target with:
     make signing-keys install
     make MACHINE=kvm_x86_64 shim-self-sign
     make MACHINE=kvm_x86_64 -j8 all demo

So Debian 8 seems to work, and the changes don't seem to have
broken newer distributions.

Signed-off-by: Alex Doyle <adoyle@nvidia.com>

diff --git a/templates/debian-package/filesystem/usr/local/bin/duebuild b/templates/debian-package/filesystem/usr/local/bin/duebuild
--- a/templates/debian-package/filesystem/usr/local/bin/duebuild
+++ b/templates/debian-package/filesystem/usr/local/bin/duebuild
@@ -105,6 +105,7 @@ function fxnHelp()
     echo "   --use-directory <dir>       cd to <dir> before trying to build."
     echo "   --prebuild-script <scr>     Run script at container path <scr> before starting build. Pass 'NONE' to ignore."
     echo "   --script-debug              Enable -x if passed as first argument."
+    echo "   --force-apt                 Apply Apt's --force-yes to override key expired/authentication errors."
     echo ""
     echo "  Debian package build options (use before --cbuild):"
     echo "   --skip-tests                Define DEB_BUILD_OPTIONS=nocheck before build."
@@ -198,6 +199,9 @@ function fxnHelpExamples()
     echo
     echo "  Build source, arch specific and type 'all' (default -uc -us)"
     echo "   $0 --cbuild "
+    echo ""
+    echo "  Force APT to ignore safeguards by applying '--force-yes' when installing dependencies."
+    echo "   $0 --force-apt --cbuild "
     echo ""
     echo "  Insert a string into the version"
     echo "   $0 --dev-version ~1234 --cbuild"
@@ -421,13 +425,14 @@ function fxnIsolatePackageDependencies()
         echo " # Attempting install of [$pkg]"
         echo " #"
         # 2 quiets to kill output
-        sudo apt-get install --quiet --quiet --assume-yes --no-install-recommends "$pkg"
+        # Use --force-yes so older versions of apt will auto-install
+        sudo apt-get install --quiet --quiet --assume-yes $APT_FORCE_YES --no-install-recommends "$pkg"
         if [ "$?" = "0" ];then
             echo "Installed [ $pkg ]"
         else
             # Run a loud install to highlight the failure
             fxnPP "Failed  [ $pkg ]. Retrying the install to get the errors."
-            sudo apt-get install --assume-yes --no-install-recommends "$pkg"
+            sudo apt-get install --assume-yes $APT_FORCE_YES --no-install-recommends "$pkg"
         fi
     done
 
@@ -509,19 +514,19 @@ function fxnDoDebianBuild()
     sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade \
          -o Dpkg::Options::="--force-confdef" \
          -o Dpkg::Options::="--force-confold" \
-         --assume-yes || fxnWARN "apt-get upgrade failed. Continuing with local index."
+         --assume-yes $APT_FORCE_YES || fxnWARN "apt-get upgrade failed. Continuing with local index."
 
     # Make sure the environment has the tools to configure the environment.
     if [ ! -e /usr/bin/mk-build-deps ];then
         fxnPP "Failed to find mk-build-deps. Installing devscripts and equivs."
-        fxnEC sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes equivs devscripts || exit 1
+        fxnEC sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes $APT_FORCE_YES equivs devscripts || exit 1
     fi
 
 
     # Create package with all needed build dependencies
     # install it
     # remove the .deb after to keep git from FREAKING OUT!
-    sudo mk-build-deps --install --remove ./debian/control --tool "apt-get -y"
+    sudo mk-build-deps --install --remove ./debian/control --tool "apt-get --assume-yes $APT_FORCE_YES"
     errorCode="$?"
     echo ""
     if [ "$errorCode" != "0" ];then
@@ -746,7 +751,6 @@ BUILD_ATTEMPTS="1"
 # Default to build after dev version string application
 JUST_DEV_VERSION="FALSE"
 
-# Default to this many build threads
 
 
 # If nproc found, default to ALL THE CORES!
@@ -828,6 +832,16 @@ do
             # Allow stacking multiple sources.list files to copy in.
             ADD_SOURCES_LIST+=" $2 "
             shift
+            ;;
+
+        --force-apt )
+            # Useful for old distributions that throw expired key errors.
+            # NOTE:  --force-yes can apply the following:
+            #  --allow-unauthenticated
+            #  --allow-downgrades
+            #  --allow-remove-essential
+            # --allow-change-held-packages
+            APT_FORCE_YES=" --force-yes "
             ;;
 
         --use-local-repo )
@@ -1190,9 +1204,9 @@ if [ "$INSTALL_DEBS_DIR" != "" ];then
         sudo DEBIAN_FRONTEND=noninteractive dpkg --force-confnew -i -- *.deb
         fxnPP "Ignore any install dependency issues from the above. Resolving with [ apt install -y -f ]"
 
-        #       sudo  apt-get install -y -f -o Dpkg::Options::="--force-confdef" || exit 1
+        # sudo  apt-get install -y -f -o Dpkg::Options::="--force-confdef" || exit 1
 
-        fxnEC sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -f || exit 1
+        fxnEC sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes -f || exit 1
 
     else
         fxnPP "No *.debs in [ $INSTALL_DEBS_DIR ]. Continuing..."
@@ -1255,7 +1269,7 @@ if [ "$DO_BUILD" = "TRUE" ];then
         buildDir=$( ls -1rd -- */ | grep "$packageName" | tail -n 1)
 
         if [ ! -e "$buildDir" ];then
-            fxnERR "Failed to find expected source directory [ $buildDir ] in [ $(pwd) ]. Exiting."         
+            fxnERR "Failed to find expected source directory [ $buildDir ] in [ $(pwd) ]. Exiting."
             exit 1
         fi
 
